name: PlayerBountiesPlus
version: '${project.version}'
main: com.tcoded.playerbountiesplus.PlayerBountiesPlus
api-version: 1.13
authors: [ TechnicallyCoded ]
description: Claim bounties only if you are not on the same clan
website: https://tcoded.com

depend:
  - Vault
  - ClansLite

commands:
  bounty:
    permission: playerbountiesplus.command.bounty
    aliases: [bounties]

permissions:
  playerbountiesplus.command.bounty:
    default: true